name:
  ResNet Alive Cron Job
 
on:
  schedule:
    - cron: "*/15 * * * *"
    
jobs:

  cron:
  
    runs-on: ubuntu-latest
 
    steps:
      - name: Execute alive test script
        run: curl -X GET https://resnet.me/cab/alive.php
